---
title: "Homework_File"
author: "Jonny Nelson"
date: "17/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(janitor)
library(tidyverse)

project_management <- read_csv("data/project_management.csv")

head(project_management)
```

# Plotting the data 

## Swap y and x 

```{r}
project_management %>%
  ggplot(aes(x = estimated_length, y = actual_length)) +
  geom_point()

# what is the one we are measuring = actual length
# what is the one we are trying to predict = estimated length

# actual length depends on estimated length, therefore dependent variable

```

# Obtaining the correlation co-efficient:

```{r}
project_management %>%
  summarise(cor = cor(actual_length, estimated_length))

# Correlation coefficient = 0.805 - this mean that estimated length is positively correlated with actual_length
```

# Model

```{r}
library(modelr)

new_model <- lm(actual_length ~ estimated_length, project_management)

summary(new_model)

# For every increase by 1 day in the the estimated length, the actual length increases by (1.2235*actual_length) with a baseline/intercept 1.4164
```

# Diagnostics

```{r}
library(ggfortify)

autoplot(new_model)

# Very strange Residual vs Fitted and Scale-Location
```

## 