---
title: "homework_attempt"
author: "Jonny Nelson"
date: "08/12/2021"
output: html_document
---

# Task 1

```{r}
library(tidyverse)
library(prob)
library(janitor)
library(infer)

house_sales <- read_csv("data/ames.csv") %>%
  clean_names()
```

# Task 2

```{r}
# Find how the data is distributed

house_sales %>%
  ggplot() +
  aes(x = lot_area) +
  geom_histogram(col = "white", fill = "steel blue") +
  labs(x = "lot area") +
  xlim(0 , 50000)

# Normally distributed with a severe right-skew
```


# Task 3 - Bootstrap Sampling

```{r}
# 1. Create the resample

resample <- house_sales %>%
  specify(response = lot_area) %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "mean")

resample

resample %>%
  ggplot() +
  aes(x = stat) +
  geom_histogram(col = "white", fill = "steel blue") +
  labs(x = "mean lot area")

```

# Task 4

```{r}
# 2. Find Confidence Level

infer_ci_95 <- resample %>%
  get_ci(level = 0.95, type = "percentile")

infer_ci_95
```

```{r}
# 3. Visualise Distribution and CI

resample %>%
  visualise(bins = 100) +
  shade_confidence_interval(endpoints = infer_ci_95)
```

```{r}
# 4. Get our point estimate

mean_infer <- resample %>%
  summarise(mean = mean(stat))

mean_infer
```


# Task 5


```{r}
# 2. Find Confidence Level

infer_ci_99 <- resample %>%
  get_ci(level = 0.99, type = "percentile")

infer_ci_99
```

```{r}
# 3. Visualise Distribution and CI

resample %>%
  visualise(bins = 100) +
  shade_confidence_interval(endpoints = infer_ci_99)
```

## Much wider CI, as expected as 99% of the samples must fit in the distribution


# Task 6


```{r}
point_estimate <- resample %>%
  summarise(mean_point_estimate = mean(stat))

point_estimate
```

