---
title: "Exploration"
author: "Jonny Nelson"
date: "27/11/2021"
output: html_document
---

```{r}
library(here)

library(tidyverse)

library(janitor)
```

```{r}
disaster_data <-  read_csv("disasters_with_errors.csv")
```

# Observations about the data

```{r}
# Using the unique function to look at the different values in the data set (handy)

unique(disaster_data$disaster_type)

# year - seems fine
# disaster type - miscellaneous (and Miscelaneous) accident, Drought (and Droght)
# iso - CHINA - needs changed -> PRC (Thought, could do a str_extract, anything not 3 cap letters) already as CHN
# There is an NA as well



mutate(iso = str_replace_all(string = iso,
                             pattern = "[CHINA]",
                             replacement = "CHN")) %

disaster_data %>%
str_extract(country_name, "[a-z]")

# come back to the str_extract

# "Cabo Verde" -> Cape Verde
# "United States of America (the)" -> take the (the) away
# Take away everything in the brackets#

russia_names <- str_c("Soviet Union", "Russian Federation", sep = "|")

yemen_names <- str_c("Yemen P Dem Rep", "Yemen Arab Rep", sep = "|")

clean_disasters <- disaster_data %>%
  select(-c(9:12)) %>%
  
  mutate(total_deaths = if_else(total_deaths >= 1 & total_deaths <= 5000000, total_deaths, as.numeric(NA))) %>%
  mutate(affected = if_else(affected >= 1 & affected <= 300000300, affected, as.numeric(NA))) %>%
  mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "\\((.*?)\\)",
                                        replacement = "")) %>%
  mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "\\,.*$",
                                        replacement = "")) %>%
  mutate(across(where(is.character), str_trim)) %>%
  
  
# Specific countries re-assigned 
  
  mutate(country_name = if_else(str_detect(country_name, russia_names), "Russia", country_name)) %>%
  mutate(country_name = if_else(str_detect(country_name, yemen_names), "Yemen", country_name)) %>%
  
  mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "Cabo Verde",
                                        replacement = "Cape Verde")) %>%
  mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "Hong Kong",
                                        replacement = "China")) %>%
  mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "Viet Nam",
                                        replacement = "Vietnam")) %>%
    mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "Canary is",
                                        replacement = "Canary Islands")) %>%
    mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "Virgin Island",
                                        replacement = "Virgin Islands")) %>%
    mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "Virgin Island",
                                        replacement = "Virgin Islands")) %>%
   mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "Germany Fed Rep",
                                        replacement = "Germany")) %>%
   mutate(country_name = str_replace_all(string = country_name,
                                        pattern = "United Kingdom of Great Britain and Northern Irela",
                                        replacement = "United Kingdom")) %>%
  
  
# Dealing with missing values
  
   mutate(occurrence = ifelse(is.na(occurrence), 1, occurrence)) %>%
   mutate(total_deaths = coalesce(total_deaths, median(total_deaths, na.rm = TRUE))) %>%
   mutate(affected = coalesce(affected, median(affected, na.rm = TRUE)))

glimpse(clean_disasters)
  
  
  
  
  
  
  
# unique(clean_disasters$country_name)  


# "Cabo Verde" = "Cape Verde"
# "Soviet Union", "Russian Federation",  = 
# "Hong Kong" = "China"
# "Viet Nam"
# "Canary Is" = "Canaray Islands"
# "Yemen Arab Rep" = "Yemen"
# R?union = "Reunion Island"
# Ivory Coast
# "Yemen P Dem Rep" = "Yemen"
# "Yugoslavia" = "Bosnia and Herzegovina, Croatia, Macedonia, Slovenia, and the Federal Republic of ..."
# "Virgin Island" = "Virgin Islands"
# "Germany Fed Rep" = "Germany"
# "United Kingdom of Great Britain and Northern Irela" = "United Kingdom"
  mutate(iso = str_replace_all(string = iso,
                               pattern = "CHINA",
                               replacement = "CHN")) %>%
  
# distaster_type 
  

  mutate(disaster_type = str_replace_all(string = disaster_type,
                                         pattern = "Droght",
                                         replacement = "Drought")) %>%
  mutate(disaster_type = str_replace_all(string = disaster_type,
                                         pattern = "Miscelaneous accident",
                                         replacement = "Miscellaneous accident")) %>%
  mutate(disaster_type = str_replace_all(string = disaster_type,
                                         pattern = "Mass movement \\(dry\\)",
                                         replacement = "Landslide")) 


# So many missing values, actually so hard to know what to do with that.

# Could replace all NA values across all columns with that columns respective 
# mean.

#    mutate(count = ifelse(is.na(count), 1, count)) %>%

# verify values fall within a given range

# total deaths - verify if in certain range  1 - 5,000,000

mutate(total_deaths = if_else(total_deaths > 1 & total_deaths < 5000000, total_deaths, as.numeric(NA)))

  mutate(age = if_else(age >= 2 & age <= 100, age, as.numeric(NA)))

# affected - verify within 1 - 300000300	
  
  mutate(affected = if_else(affected > 1 & affected < 300000300, affected, as.numeric(NA)))



# get ride of anything after this 

names(clean_disasters)

select(-c(10:12))










getwd()

# need to trim white-space as well

unique(clean_disasters$)


clean_disasters %>%
  slice_max(total_deaths)

# clean_disasters %>%
#   select(iso, country_name, occurrence) %>%
#   filter(is.na(clean_disasters$iso))
```